// Shared goal-state shape used by new-goal creation and persisted-state recovery.
export function baseGoalState(fields = {}) {
  const {
    sessionID,
    goalInstanceID,
    condition,
    successCriteria = "",
    constraints = "",
    verifyCommand = "",
    observe = false,
    status = "active",
    startedAt,
    updatedAt = startedAt,
    generation = 0,
    turns = 0,
    maxTurns,
    hiddenCalls = 0,
    maxHiddenCalls,
    maxGoalDurationMs,
    deadlineAt,
    minDelayMs,
    maxPromptFailures,
    noProgressTokenThreshold,
    noProgressTurnsBeforePause,
    noToolCallTurnsBeforePause,
    lastReason = "",
    lastConfidence = "",
    lastEvidenceGaps = [],
    lastCriteria = [],
    lastNextSteps = [],
    lastVerifyResult = null,
    lastEvidence = "",
    blockedReason = "",
    stopReason = "",
    lastResearchAtTurn = undefined,
    lastResearchMessageID = "",
    lastResearchReport = "",
    initialAgent = undefined,
    lastAgent = undefined,
    initialModel = undefined,
    lastModel = undefined,
    promptFailures = 0,
    lastContinueAt = 0,
    pausedAt = 0,
    accumulatedPausedMs = 0,
    noProgressTurns = 0,
    noToolCallTurns = 0,
    lastAssistantText = "",
    lastAssistantMessageID = "",
    lastEvaluatedMessageID = "",
    lastProgressMessageID = "",
    history = [],
    evaluating = false,
    continuing = false,
    evaluatingRun = null,
    continuingRun = null,
    blocked = false,
    suppressNextIdle = false,
    humanInterrupted = false,
  } = fields;

  return {
    sessionID,
    goalInstanceID,
    condition,
    successCriteria,
    constraints,
    verifyCommand,
    observe,
    status,
    startedAt,
    updatedAt,
    generation,
    turns,
    maxTurns,
    hiddenCalls,
    maxHiddenCalls,
    maxGoalDurationMs,
    deadlineAt,
    minDelayMs,
    maxPromptFailures,
    noProgressTokenThreshold,
    noProgressTurnsBeforePause,
    noToolCallTurnsBeforePause,
    lastReason,
    lastConfidence,
    lastEvidenceGaps,
    lastCriteria,
    lastNextSteps,
    lastVerifyResult,
    lastEvidence,
    blockedReason,
    stopReason,
    lastResearchAtTurn,
    lastResearchMessageID,
    lastResearchReport,
    initialAgent,
    lastAgent,
    initialModel,
    lastModel,
    promptFailures,
    lastContinueAt,
    pausedAt,
    accumulatedPausedMs,
    noProgressTurns,
    noToolCallTurns,
    lastAssistantText,
    lastAssistantMessageID,
    lastEvaluatedMessageID,
    lastProgressMessageID,
    history,
    evaluating,
    continuing,
    evaluatingRun,
    continuingRun,
    blocked,
    suppressNextIdle,
    humanInterrupted,
  };
}
